### ISSUE TITLE
Print (best/worst) line for each move

### ISSUE THREAD

**Issue by MrPiada** [Destaq/chess_graph#10]
First of all GREAT WORK ! Amazing tool ;)

I kindly ask you the possibility to print (at least on terminal or on a .txt file) the best (W/B ratio) and worst line for each level.
Something like:
| Move | Best (W/B, ngames) | Worst (W/B, ngames) |
| ------- | --------------------------- | ----------------------------- | 
| 1              | 1.e4  (0.6, 10)               | 1.d4 (0.4, 12) |
| 2              | 1.e4 e5 (0.5, 8)             | 1.d4  Nf6 (0.3, 9) |
and so on....

I'm available to help you doing this (just send me an email)

**Comment by Destaq** [comment]
Hi, thank you for your kind feedback! I'm glad you find the project useful.

It's been over half a year since I've last worked on the project, and I've strayed a bit from chess since then. But if you familiarize yourself with the code, I'd be happy to merge a PR that performs the above feature.

If you do decide to make it, please ensure that the argument is *optional* and its usage defined.

**Comment by MrPiada** [comment]
Actually I've never done a PR myself...

btw I've already produced the chart.py with the new feature and I have an example to run it.

Could you help me to implement them ? :)

**Comment by Destaq** [comment]
I'm glad you were able to get it up and running on your local fork.

You can consult the below GitHub guide to create a pull request based on a fork:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by MrPiada** [comment]
PR done ;)

**Comment by Destaq** [comment]
Merged.
